services:
  dd:
    image: gcr.io/datadoghq/agent:latest
    container_name: dd-agent
    environment:
      - DD_API_KEY=90e097e51a9edbfdad5fc292c65fbbb0
      - DD_APM_ENABLED=true
      - DD_SITE=datadoghq.eu
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_ENV=dev
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_RECEIVER_SOCKET=/var/run/datadog/apm.socket
      - DD_TRACE_AGENT_URL=unix:///var/run/datadog/apm.trace
      - DD_DOGSTATSD_SOCKET=/var/run/datadog/dsd.socket
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
      - DD_LOGS_ENABLED=true
      - DD_OTLP_CONFIG_LOGS_ENABLED=true
    volumes:
      - /var/run/datadog:/var/run/datadog
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8126:8126"
      - "4317:4317"
      - "4318:4318"